trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildAndPublish
    displayName: 'Build and Publish Package'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.10'
        inputs:
          versionSpec: '3.10'
          addToPath: true
          architecture: "x64"

      - task: PythonScript@0
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
          arguments: "--token $SYSTEM_ACCESSTOKEN"
          scriptSource: 'inline'
          script: |
            import argparse
    
            if __name__ == "__main__":
              parser = argparse.ArgumentParser()
              parser.add_argument("token")
              args = parser.parse_args()
              print(args.token) 

      - script: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.5.1 python3 -
        displayName: "Install poetry 1.5.1"

      - script: |
          build_number=$(echo '$(Build.BuildNumber)' | sed 's/\.//g')
          echo $build_number
          poetry config repositories.devops https://pkgs.dev.azure.com/rafaelpmiranda0166/_packaging/rafaelpmiranda0166/pypi/upload/
          poetry config http-basic.devops anything $SYSTEM_ACCESSTOKEN
          poetry publish --repository devops --build
        displayName: 'Build and Publish Package'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
